image : node:latest

stages :
 - build
 - test
 - deploy
 
build_stage :
 stage : build
 script :
 - npm init -y
 - npm install --save
 - npm install discord.js --save
 - npm install discord.js-commando --save
 - npm install request --save
 - npm install cheerio --save
 - ls -a
 - node ./index.js
 